### ISSUE TITLE
Getting error while trying run

### ISSUE THREAD

**Issue by Lunedor** [deandreamatias/tv-randshow#1]
I was trying to work this project but after I install in android studio then tried to work it gets below message.

--
Compiler message:
lib/main_dev.dart:6:8: Error: Error when reading 'lib/config/env.dart': Sistem belirtilen dosyayı bulamıyor.

import 'config/env.dart';
       ^

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Lunedor\AndroidStudioProjects\tv-randshow\android\app\build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 1s
Running Gradle task 'assembleDevDebug'...
Running Gradle task 'assembleDevDebug'... Done                      2,6s
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:273:8: Error: The method 'FlushbarRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
/C:/Src/flutter/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
  void install() {
       ^
lib/main_dev.dart:13:66: Error: Getter not found: 'environment'.
  FlavorConfig(flavor: Flavor.DEV, values: FlavorValues.fromJson(environment));
                                                                 ^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:281:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
Exception: Gradle task assembleDevDebug failed with exit code 1

--

**Comment by deandreamatias** [comment]
Hi @Lunedor 
This error is because you need create this file to run project. In this file, have a baseUrl and a apiKey. Api key you get from TMDB (see this [FAQ ](https://www.themoviedb.org/faq/api) for more details) and paste in new file (config/env.dart) like this:
```dart
const Map<String, String> environment = <String, String>{
  'baseUrl': 'api.themoviedb.org',
  'apiKey': 'YOUR API KEY HERE'
};
```
I'll update the readme with this info to future references

**Comment by deandreamatias** [comment]
I update the readme in [this commit](https://github.com/deandreamatias/tv-randshow/commit/69f6cdff7899f5a6631d605dc218fbf93e32331a)
