### ISSUE TITLE
New Contribution request.

### ISSUE THREAD

**Issue by Pranshul2002** [deandreamatias/tv-randshow#3]
## Environment

**App version:**    
**Android version:**  10
**Device information:**  OnePlus 7

## Description

**What you'd like to happen:** 
When there is no favourites selected show text that no favourites instead of the normal screen.

**Comment by deandreamatias** [comment]
Like this?

![Screenshot_20200930-083048.jpg](https://user-images.githubusercontent.com/21011641/94650610-54558300-02f7-11eb-998d-3ad76a7e1d66.jpg)

**Comment by Pranshul2002** [comment]
Ohh yeah. I didn't see that. If there is anything I could help you
with please let me know. I am a flutter developer too. I made an app.
https://play.google.com/store/apps/details?id=com.manipal_locals.android
