### ISSUE TITLE
APKs missing from the last 2 releases

### ISSUE THREAD

**Issue by IzzySoft** [deandreamatias/tv-randshow#9]
Your last 2 releases have no APKs attached anymore. Could you please attach it again to the latest one (and to future ones as well)? Thanks in advance!

**Comment by deandreamatias** [comment]
Hi!
I upload the apk for the last release (2.0.1).
I will add the APK for the next releases in the future too

**Comment by IzzySoft** [comment]
Thanks a lot! Updated then at my end. Btw, your app is [available in my repo](https://apt.izzysoft.de/packages/deandrea.matias.tv_randshow/), so if you wish you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) (or two) to accompany the Google Play Store one(s) and have it/them pointing there :smiley:

**Comment by deandreamatias** [comment]
Ooh, really nice to know.
I take a look on this and add on the readme. Thanks!

**Comment by IzzySoft** [comment]
Great! Looking forward to the badge(s) showing up then :smiley:

**Comment by deandreamatias** [comment]
Done!

**Comment by IzzySoft** [comment]
Not yet pushed it seems? Ah, I see one of the badged in the develop branch, yeah :v:
